### ISSUE TITLE
Set Up Basic Client-Server Communication

### ISSUE THREAD

**Issue by Sewerbird** [Sewerbird/Helios2400#78]
Alright, so coming into April after hiatus, the game design has changed a bit. We now will have a server-client setup to facilitate multiplayer games, and that means we need to implement send/receive capabilities in the LUA client. 

**You've carte blanche to implement a means by which the Helios LUA client can emit and receive JSON/datagrams to a remote server.**

A good solution, in my opinion, would handle bad internet well: if we go websockets, I'd like the library we use to fall back gracefully to polling. The target server is going to be in Node.js, and you can peek at the existing skeleton I've gotten up on `master`.

- [x] Can hit an endpoint (ping/hello world)
- [x] Can emit a packet of information (format doesn't matter yet)
- [x] If using a socket, demonstrate (with a toy server, or altering our skeleton Node server) that the client can receive a pushed message from the server

**Comment by thimovss** [comment]
Example available in separate repo.
