### ISSUE TITLE
Wireframe Title Screen

### ISSUE THREAD

**Issue by Sewerbird** [Sewerbird/Helios2400#79]
Using LoveGUI, implement a title screen that appears when you first launch the game. It should have the following aspects:

  - [x] "Helios 2400" as a big-text title
  - [x] "Join A Game" button below that: Launches the Join Dialog
  - [x] "Exit Helios" button below that: Exits the Game
  - [x] All centered
  - [ ] (Extra Credit) A 'background' element with a partially-terraformed Martian horizon with a starfield above it. A raster image or software-drawn vector graphics are both acceptable

  - [x] A Join Dialog
    - [x] Grays out and stops clicks on the Title Screen
    - [x] Has a text panel saying `Enter the address of the game you wish to join`
    - [x] Has a text input field where you can type in an address. 
    - [x] Text input field defaults to `localhost:50000` for now (assuming [a local server](https://github.com/thimovss/HeliosSocketExample/blob/master/src/server/app.js))
    - [x] Has a 'Join' button that sends a CONNECT message to the server
    - [x] Once the CONNECT message succeeds, it triggers a change to the Game Lobby screen
    - [x] If the CONNECT message fails, the text panel switches to saying `Connection Failed! Please try again`
    - [x] Has a 'Cancel' button that ends the Join Dialog and re-enables clicking on the Title Screen

Fine art-direction isn't super important at this point: color things kind of purple-ish with grays. The Game Lobby screen is detailed in another issue.

**Comment by thimovss** [comment]
Moved 
Has a 'Join' button that sends a CONNECT message to the server
and Once the CONNECT message succeeds, it triggers a change to the Game Lobby screen
to separate issue
