### ISSUE TITLE
Persistent (Debug) Identity

### ISSUE THREAD

**Issue by Sewerbird** [Sewerbird/Helios2400#81]
Each Helios client that runs should have a unique identity, that way we can have a username for players and have them be able to re-join a game correctly. As such, we should be able to launch the client with a `username` parameter that gets associated with all connections that client makes. Later on, we'll make this more sophisticated (so people can't just rename themselves to another person's name to impersonate them), but this should be enough for now. We need:

- [x] The ability to launch `love . --username 'Edward'` and thus have the string `Edward` available to the game code
- [x] Store `Edward` in a global variable alled `CLIENT_USERNAME`
- [ ] Send this string along in all `CONNECT` and `DISCONNECT` messages to the server

**Comment by thimovss** [comment]
Moved  Send this string along in all CONNECT and DISCONNECT messages to the server to separate issue
